tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "1password/tap"
brew "bat" # cat clone with syntax highlighting
brew "exa" # modern replacement for ls
brew "exercism"
brew "figlet" # print strings as ASCII art
brew "fzf" # command-line fuzzy finder
brew "gh" # github command-line tool
brew "go"
brew "gnupg" # for installing rvm
brew "lorem" # lorem ipsum generator
brew "rust"
brew "pandoc" # markup format conversion
brew "prettier"
brew "pure" # minimal prompt for zsh
brew "pyenv" # python manager
brew "shellcheck" # ling shell scripts
brew "tldr" # community-driven man pages
brew "tmux"
brew "tree" # display directories as trees
brew "wget" # internet file retriever
cask "1password"
cask "1password-cli"
cask "arc" # browser
cask "discord"
cask "google-drive"
cask "iterm2"
cask "obsidian"
cask "rectangle" # resize windows with keyboard
cask "signal"
cask "slack"
cask "spotify"
cask "todoist"
cask "visual-studio-code"
cask "zulip"
